"""Domain constants."""

PROJECT_STATUS_ACTIVE = "active"
PROJECT_STATUS_COMPLETED = "completed"

GOAL_STATUS_ACTIVE = "active"
GOAL_STATUS_COMPLETED = "completed"

GOAL_TYPE_REQUIREMENT = "requirement"
GOAL_TYPE_ISSUE = "issue"
GOAL_TYPES = {GOAL_TYPE_REQUIREMENT, GOAL_TYPE_ISSUE}

REMINDER_NEAR = "near"
REMINDER_OVERDUE = "overdue"
REMINDER_MISSING_UPDATE = "missing_update"

REPORT_DAILY = "daily"
REPORT_WEEKLY = "weekly"
REPORT_MONTHLY = "monthly"
REPORT_PERIODS = {REPORT_DAILY, REPORT_WEEKLY, REPORT_MONTHLY}

EMAIL_STATUS_SENT = "sent"
EMAIL_STATUS_FAILED = "failed"

ROLE_ADMIN = "admin"
ROLE_OWNER = "owner"
ROLES = {ROLE_ADMIN, ROLE_OWNER}
