"""Domain constants."""

PROJECT_STATUS_ACTIVE = "active"
PROJECT_STATUS_COMPLETED = "completed"

GOAL_STATUS_ACTIVE = "active"
GOAL_STATUS_COMPLETED = "completed"

GOAL_TYPE_REQUIREMENT = "requirement"
GOAL_TYPE_ISSUE = "issue"
GOAL_TYPE_TASK = "task"
GOAL_TYPES = {GOAL_TYPE_REQUIREMENT, GOAL_TYPE_ISSUE, GOAL_TYPE_TASK}

PROGRESS_STATE_NORMAL = "normal"
PROGRESS_STATE_DELAYED = "delayed"
PROGRESS_STATE_AHEAD = "ahead"
PROGRESS_STATES = {PROGRESS_STATE_NORMAL, PROGRESS_STATE_DELAYED, PROGRESS_STATE_AHEAD}

REMINDER_NEAR = "near"
REMINDER_OVERDUE = "overdue"
REMINDER_MISSING_UPDATE = "missing_update"

REPORT_DAILY = "daily"
REPORT_WEEKLY = "weekly"
REPORT_MONTHLY = "monthly"
REPORT_PERIODS = {REPORT_DAILY, REPORT_WEEKLY, REPORT_MONTHLY}

EMAIL_STATUS_SENT = "sent"
EMAIL_STATUS_FAILED = "failed"

ROLE_ADMIN = "admin"
ROLE_OWNER = "owner"
ROLES = {ROLE_ADMIN, ROLE_OWNER}
